from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class admin_handle(models.Model):
    user_name = models.CharField(max_length=20,blank=True)
    admin_charge = models.IntegerField(default=0)
    tax_gst = models.IntegerField(default=0)
    spon_income = models.IntegerField(default=0)
    spon_month_income = models.IntegerField(default=0)
    lvl_income = models.IntegerField(default=0)
    l1_income = models.IntegerField(default=0)
    l2_income = models.IntegerField(default=0)
    l3_income = models.IntegerField(default=0)
    l4_income = models.IntegerField(default=0)
    l5_income = models.IntegerField(default=0)
    l6_income = models.IntegerField(default=0)
    l7_income = models.IntegerField(default=0)
    l8_income = models.IntegerField(default=0)
    l9_income = models.IntegerField(default=0)
    bonus = models.IntegerField(default=0)
    next_payout_date = models.DateField(null=True,blank=True)



class GeneralHome(models.Model):
    latest_date = models.DateTimeField(blank=True,null=True)
    status = models.CharField(max_length=20,blank=True)
    hightlightword = models.CharField(max_length=50,blank=True)
    hightlight_descriptions = models.TextField(max_length=200,blank=True)
    about_heading = models.TextField(max_length=200,blank=True)
    about_descriptions = models.TextField(max_length=4000,blank=True)
    product_heading = models.TextField(max_length=200,blank=True)
    product_heading_1 = models.CharField(max_length=20,blank=True)
    product_desc_1 = models.CharField(max_length=70,blank=True)
    product_image_1 = models.ImageField(upload_to="General",blank=True)
    product_heading_2 = models.CharField(max_length=20,blank=True)
    product_desc_2 = models.CharField(max_length=70,blank=True)
    product_image_2 = models.ImageField(upload_to="General",blank=True)
    product_heading_3 = models.CharField(max_length=20,blank=True)
    product_desc_3 = models.CharField(max_length=70,blank=True)
    product_image_3 = models.ImageField(upload_to="General",blank=True)
    product_heading_4 = models.CharField(max_length=20,blank=True)
    product_desc_4 = models.CharField(max_length=70,blank=True)
    product_image_4 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading = models.TextField(max_length=300,blank=True)
    glimpses_heading_1 = models.CharField(max_length=50,blank=True)
    glimpses_desc_1 = models.TextField(max_length=200,blank=True)
    glimpses_image_1 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading_2 = models.CharField(max_length=50,blank=True)
    glimpses_desc_2 = models.TextField(max_length=200,blank=True)
    glimpses_image_2 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading_3 = models.CharField(max_length=50,blank=True)
    glimpses_desc_3 = models.TextField(max_length=200,blank=True)
    glimpses_image_3 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading_4 = models.CharField(max_length=50,blank=True)
    glimpses_desc_4 = models.TextField(max_length=200,blank=True)
    glimpses_image_4 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading_5 = models.CharField(max_length=50,blank=True)
    glimpses_desc_5 = models.TextField(max_length=200,blank=True)
    glimpses_image_5 = models.ImageField(upload_to="General",blank=True)
    glimpses_heading_6 = models.CharField(max_length=50,blank=True)
    glimpses_desc_6 = models.TextField(max_length=200,blank=True)
    glimpses_image_6 = models.ImageField(upload_to="General",blank=True)
    offer_heading = models.TextField(max_length=300,blank=True)
    offer_heading_1 = models.CharField(max_length=50,blank=True)
    offer_desc_1 = models.TextField(max_length=200,blank=True)
    offer_image_1 = models.ImageField(upload_to="General",blank=True)
    offer_heading_2 = models.CharField(max_length=50,blank=True)
    offer_desc_2 = models.TextField(max_length=200,blank=True)
    offer_image_2 = models.ImageField(upload_to="General",blank=True)
    offer_heading_3 = models.CharField(max_length=50,blank=True)
    offer_desc_3 = models.TextField(max_length=200,blank=True)
    offer_image_3 = models.ImageField(upload_to="General",blank=True)

class MemberHome(models.Model):
    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    status = models.CharField(max_length=20,blank=True)
    slide_heading = models.CharField(max_length=50,blank=True)
    slide_desc = models.TextField(max_length=200,blank=True)
    slide_image = models.ImageField(upload_to="General",blank=True)
    
class Withdraw(models.Model):
    withdraw_no = models.AutoField
    request_no = models.CharField(max_length=30,blank=True)
    member_name = models.CharField(max_length=50,blank=True)
    member_id = models.CharField(max_length=20,blank=True)
    amount = models.IntegerField(default=0)
    status = models.CharField(max_length=20,blank=True)
    request_date = models.DateTimeField(auto_now_add=True,blank=True)
    with_type = models.CharField(max_length=20,blank=True)
    withdraw_ref = models.CharField(max_length=30,blank=True)
    withdraw_date = models.DateTimeField(blank=True, null=True)
    remarks = models.CharField(max_length=100,blank=True)


class Staff_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default = "")
    staff_id = models.CharField(max_length=20)
    user_image = models.ImageField(upload_to="myAdmin/images",blank=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    contact = models.CharField(max_length=10)
    email = models.EmailField(max_length=50, blank=True,null=True)
    rights = models.CharField(max_length=30)
    designation = models.CharField(max_length=50)
    creator_name = models.CharField(max_length=50)
    creator_id = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    pin = models.CharField(max_length=6)
    state = models.CharField(max_length=20)
    pan_number = models.CharField(max_length=10, blank=True)
    pan_image = models.FileField(upload_to="myAdmin/images",blank=True)
    adhaar_number = models.CharField(max_length=12, blank=True)
    adhaar_image = models.FileField(upload_to="myAdmin/images",blank=True)
    passport = models.CharField(max_length=20, blank=True)
    passport_image = models.FileField(upload_to="myAdmin/images",blank=True)
    voter_id = models.CharField(max_length=20, blank=True)
    voter_id_image = models.FileField(upload_to="myAdmin/images",blank=True)
    account_number = models.CharField(max_length=20, blank=True)
    account_holder_name = models.CharField(max_length=20, blank=True)
    bank_name = models.CharField(max_length=20, blank=True)
    branch_name = models.CharField(max_length=20, blank=True)
    ifsc_code = models.CharField(max_length=20, blank=True)
    branch_city = models.CharField(max_length=20, blank=True)
    passbook_image = models.FileField(upload_to="myAdmin/images",blank=True)
    cheque_image = models.FileField(upload_to="myAdmin/images",blank=True)

    class Meta:  
        db_table = "Staff_User"

    @property
    def full_name(self):
        return "%s %s"%(self.first_name, self.last_name)